<a href="https://colab.research.google.com/github/PlayTrain99/data-sciences/blob/main/second_lesson_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Type Danych numpy array

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [3]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [4]:
A = np.array([1.0, 2.6, 3.8], dtype="int")
A.dtype

dtype('int64')

In [5]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [6]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Tworzenie tablic

In [7]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.zeros(shape=(4,10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones(shape=(5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [11]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(start=0, stop=101, step=10, dtype="float")

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
A.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Operacja na tablicach

In [17]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
C = np.array([6, -3, 1, 5])

In [18]:
A + B

array([6, 0, 7, 4])

In [19]:
A - B

array([0, 2, 1, 0])

In [20]:
A + 3

array([6, 4, 7, 5])

In [21]:
np.add(A, C)

array([ 9, -2,  5,  7])

In [22]:
np.subtract(A, C)

array([-3,  4,  3, -3])

In [28]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y, "\n")

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]] 



In [27]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [29]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [30]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# Liczby losowe

In [33]:
np.random.seed(0)

In [34]:
np.random.randn()

1.764052345967664

In [36]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [41]:
np.random.rand()

0.8379449074988039

In [42]:
np.random.rand(10)

array([0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552,
       0.73926358, 0.03918779, 0.28280696, 0.12019656, 0.2961402 ])

In [46]:
np.random.randint(low = 10, high=22, size=3)

array([12, 13, 21])

In [50]:
np. random.choice([4, 2, 1, 3, 5])

5

In [51]:
date = np.arange(10)
date

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.random.shuffle(date)
date

array([4, 9, 1, 8, 7, 3, 0, 5, 2, 6])

# Podstawowe funkcje

In [77]:
np.exp(1)

2.718281828459045

In [78]:
np.sqrt(9)

3.0

In [79]:
np.all([2, 3, 2])

True

In [80]:
np.any([0, 0, 0])

False

In [81]:
A = np.random.rand(5)
A

array([0.75610669, 0.39609828, 0.89603839, 0.63892108, 0.89155444])

In [82]:
np.argmax(A)

2

In [83]:
np.argmax(A)

2

In [84]:
np.argmin(A)

1

In [85]:
np.argsort(A)

array([1, 3, 0, 4, 2])

In [86]:
np.max(A)

0.896038387509077

# Indeksowanie i wycinanie

In [87]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [91]:
A[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [93]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [95]:
A[2]

array([10, 11, 12, 13, 14])

In [98]:
A[:, 2] #Kolumna

array([ 2,  7, 12, 17])

In [99]:
A[2, :] #Wiersz

array([10, 11, 12, 13, 14])

In [104]:
A[2,1]

11

In [105]:
A[2,1] = 29
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 29, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [107]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 29, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 29 12 13 14]
[15 16 17 18 19]


In [110]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 29 12]
[15 16 17]


In [111]:
for item in A.flat:
  print(item)


0
1
2
3
4
5
6
7
8
9
10
29
12
13
14
15
16
17
18
19


# Zmiana rozmiaru tablic

In [112]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 29, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [114]:
A.shape

(4, 5)

In [115]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 29],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [117]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 29, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 29, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [120]:
A = np.arange( start=-10, stop = 10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [121]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [122]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [125]:
np.bitwise_and(A>-5, A <5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [124]:
A[np.bitwise_and(A>-5, A <5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [127]:
np.bitwise_or(A>-5, A > 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])