<a href="https://colab.research.google.com/github/PlayTrain99/data-sciences/blob/main/second_lesson_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Type Danych numpy array

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [3]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [4]:
A = np.array([1.0, 2.6, 3.8], dtype="int")
A.dtype

dtype('int64')

In [5]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [6]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Tworzenie tablic

In [7]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.zeros(shape=(4,10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones(shape=(5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [11]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(start=0, stop=101, step=10, dtype="float")

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
A.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Operacja na tablicach

In [17]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
C = np.array([6, -3, 1, 5])

In [18]:
A + B

array([6, 0, 7, 4])

In [19]:
A - B

array([0, 2, 1, 0])

In [20]:
A + 3

array([6, 4, 7, 5])

In [21]:
np.add(A, C)

array([ 9, -2,  5,  7])

In [22]:
np.subtract(A, C)

array([-3,  4,  3, -3])

In [28]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y, "\n")

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]] 



In [27]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [29]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [30]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# Liczby losowe

In [33]:
np.random.seed(0)

In [34]:
np.random.randn()

1.764052345967664

In [36]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [41]:
np.random.rand()

0.8379449074988039

In [42]:
np.random.rand(10)

array([0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552,
       0.73926358, 0.03918779, 0.28280696, 0.12019656, 0.2961402 ])

In [46]:
np.random.randint(low = 10, high=22, size=3)

array([12, 13, 21])

In [50]:
np. random.choice([4, 2, 1, 3, 5])

5

In [51]:
date = np.arange(10)
date

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.random.shuffle(date)
date

array([4, 9, 1, 8, 7, 3, 0, 5, 2, 6])

# Podstawowe funkcje

In [56]:
np.exp(1)

2.718281828459045

In [57]:
np.sqrt(9)

3.0

In [60]:
np.all([2, 3, 2])

True

In [63]:
np.any([0, 0, 0])

False

In [69]:
A = np.random.rand(5)
A

array([0.14644176, 0.56961841, 0.70373728, 0.28847644, 0.43328806])

In [72]:
np.argmax(A)

2

In [71]:
np.argmax(A)

0.7037372792899163

In [73]:
np.argmin(A)

0

In [74]:
np.argsort(A)

array([0, 3, 4, 1, 2])

In [76]:
np.max(A)

0.7037372792899163