<a href="https://colab.research.google.com/github/PlayTrain99/data-sciences/blob/main/second_lesson_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Type Danych numpy array

In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [3]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [4]:
A = np.array([1.0, 2.6, 3.8], dtype="int")
A.dtype

dtype('int64')

In [5]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [6]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Tworzenie tablic

In [7]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.zeros(shape=(4,10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones(shape=(5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [11]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(start=0, stop=101, step=10, dtype="float")

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
A.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Operacja na tablicach

In [17]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
C = np.array([6, -3, 1, 5])

In [18]:
A + B

array([6, 0, 7, 4])

In [19]:
A - B

array([0, 2, 1, 0])

In [20]:
A + 3

array([6, 4, 7, 5])

In [21]:
np.add(A, C)

array([ 9, -2,  5,  7])

In [22]:
np.subtract(A, C)

array([-3,  4,  3, -3])

In [28]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, "\n")
print(Y, "\n")

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]] 



In [27]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [29]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [30]:
X @ Y

array([[  3,   6],
       [-12,   0]])