<a href="https://colab.research.google.com/github/PlayTrain99/data-sciences/blob/main/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.__version__

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [16]:
y = np.array([1.3, 2.3, 1.4])
print(y)

[1.3 2.3 1.4]


In [17]:
y.dtype

dtype('float64')

tablica 2 wymiary

In [21]:
b = np.array([[1, 2], [-3 , 1]])

In [22]:
b.ndim

2

In [23]:
b.shape

(2, 2)

In [25]:
x = np.array([[1, 2, 4], [4, 2, 1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [26]:
x.shape

(2, 3)

tablice 3 wymiary

In [35]:
x = np.array(
    [[[4, 3, 1],
     [3, 1, 2]],

    [[4, 1, 3],
     [4, 2 , 1]],

     [[3, 2, 1],
      [5, 6, 7]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [5, 6, 7]]])

In [36]:
x.ndim

3

In [37]:
x.shape

(3, 2, 3)