<a href="https://colab.research.google.com/github/PlayTrain99/data-sciences/blob/main/third_lesson_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.26.4'

# Norma wekotra

In [6]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1)

4.123105625617661

In [8]:
v2 = np.array([-10, 10 ,13])

In [9]:
np.linalg.norm(v2)

19.209372712298546

# Odległosć dówch punktów na płaszczyźnie

In [11]:
p = np.array([3, 0])
q = np.array([0, 4])

In [13]:
np.linalg.norm(p - q)

5.0

# Odległosć dówch punktów w przestrzeni

In [14]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

In [15]:
np.linalg.norm(p - q)

5.0990195135927845

# Liczenie macierzy

In [17]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [19]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [20]:
Z.shape

(2, 1)

In [26]:
X = np.array([[2, -1 , 3],
              [3, 1, 0]])
Y = np.array([[2, 1,-1],
              [0, -1, 2],
              [3, 2, 0]])
print(X)
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]
[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [27]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

# Rówanie liniowe

In [29]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [28]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [30]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [31]:
X.shape

(2, 1)

In [32]:
X.ndim

2